version: '3.8'

volumes:
  ubuntu:


services:

  Sample:
    image: "ubuntu"
    container_name: ubuntu
    user: 'ubuntu'
    working_dir: '/home/'
    build:
      context: .
    environment:
      - DEBIAN_FRONTEND=noninteractive
    ports:
      - 4000:4000

    volumes:
      - ubuntu
